version: 2.1

jobs:
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- The images is Building ------------"

            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend ./udagram-frontend
            docker build -t reverseproxy ./udagram-reverseproxy 

            docker tag udagram-api-feed phamvanquang/udagram-api-feed:v1
            docker tag udagram-api-user phamvanquang/udagram-api-user:v1
            docker tag udagram-frontend phamvanquang/udagram-frontend:v1
            docker tag reverseproxy phamvanquang/reverseproxy:v1

            echo "-------- All images succesfully built----------"

      - run:
          name: Docker login
          command: | 
            echo " ------- login in to hub--------"

            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            echo " ------- Successfully-----------"

      - run:
          name: Pushing Images to DockerHub
          command: |

            echo "-------------- Pushing images to dockerhub-------"

            docker push phamvanquang/udagram-api-feed:v1
            docker push phamvanquang/udagram-api-user:v1
            docker push phamvanquang/udagram-frontend:v1
            docker push phamvanquang/reverseproxy:v1

            echo "-------------- Pushing images to dockerhub Success-------"

workflows:
  default:
    jobs:
      - build-docker